import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const vcrjp = localFont({
  src: "../public/fonts/vcr-jp.ttf",
  variable: "--font-vcr-jp",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${vcrjp.variable} h-full antialiased scroll-smooth!`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
